# Generated by Django 2.1.7 on 2019-05-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190430_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal_code',
            name='postal_code',
            field=models.IntegerField(db_index=True),
        ),
    ]
