# Generated by Django 2.1.7 on 2019-04-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190426_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postal_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('postal_code',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zipcode', to='orders.Postal_Code'),
        ),
    ]
