# Generated by Django 2.1.7 on 2019-05-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190430_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='postal_code',
            name='postal_code',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
