# Generated by Django 2.1.7 on 2019-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190426_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal_code',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
