# Generated by Django 2.1.7 on 2019-04-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190426_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postal_code',
            options={'ordering': ('postal_code',), 'verbose_name': 'Postal Code', 'verbose_name_plural': 'Postal Codes'},
        ),
    ]
