# Generated by Django 2.1.7 on 2019-05-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190430_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='home_delivery',
        ),
    ]
